version: 3

vars:
  GEN_DIR: tmp/genproto
  GEN_ROOT: "{{ .GEN_DIR }}/github.com/be9/protogobazel/lib/proto"

tasks:
  setup:
    cmds:
      - go mod download
      - go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
      - go install github.com/golang/protobuf/protoc-gen-go
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

  genproto:
    cmds:
      - rm -rf {{ .GEN_DIR }}
      - mkdir -p {{ .GEN_DIR }}
      - for: ['foo/foo.proto foo/foo_enum.proto', 'bar/bar.proto']
        cmd: >
          protoc -I proto/src  
          --grpc-gateway_out=logtostderr=true:{{ .GEN_DIR }}
          --go_out=plugins=grpc:{{ .GEN_DIR }}
          --grpc-gateway_opt generate_unbound_methods=true
          --grpc-gateway_opt paths=source_relative
          ./proto/src/{{ .ITEM }}
      - rm -rf lib/proto/*
      - cp -r {{ .GEN_ROOT }}/* lib/proto/
